import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import {
  commitBoms,
  commitDrums,
  commitRawMaterials,
  memoryImportStores,
  previewKind,
} from './importPipelineService';

describe('Increment 2 import validation', () => {
  it('keeps a blank raw-material price as PRICE_NOT_CONFIGURED, never zero', () => {
    const stores = memoryImportStores();
    const result = commitRawMaterials(
      [
        {
          'Raw Material Code': 'CR01',
          Description: 'Copper rod',
          'Unit of Measurement': 'kg',
          Price: '',
        },
      ],
      'Raw Material List.xlsx',
      'tester',
      { persist: true, stores }
    );
    assert.equal(result.batch.status, 'COMMITTED');
    assert.equal(result.rawMaterials?.[0].price, null);
    assert.equal(result.rawMaterials?.[0].priceStatus, 'PRICE_NOT_CONFIGURED');
    assert.notEqual(result.rawMaterials?.[0].price, 0);
    assert.equal(stores.getRawMaterials()[0].price, null);
    assert.ok(result.batch.warnings.some((w) => w.code === 'PRICE_NOT_CONFIGURED'));
  });

  it('updates an existing Drum Code instead of creating a duplicate', () => {
    const stores = memoryImportStores();
    commitDrums(
      [
        {
          'Drum Code': 'EWD900-0',
          Flange: 900,
          Barrel: 450,
          'Inner Width': 500,
          'Outer Width': 700,
          Capacity: 800,
        },
      ],
      'Drum List.xlsx',
      'tester',
      { persist: true, stores }
    );
    const updated = commitDrums(
      [
        {
          'Drum Code': 'EWD900-0',
          Flange: 900,
          Barrel: 450,
          'Inner Width': 500,
          'Outer Width': 700,
          Capacity: 800,
          'Empty Drum Net Weight Kg': 70,
        },
      ],
      'Energya_Drum_Master_Upload_Template.xlsx',
      'tester',
      { persist: true, stores }
    );
    assert.equal(updated.batch.status, 'COMMITTED');
    assert.equal(stores.getDrums().length, 1);
    assert.equal(stores.getDrums()[0].drumCode, 'EWD900-0');
    assert.equal(stores.getDrums()[0].emptyDrumNetWeightKg, 70);
    assert.equal(stores.getDrums()[0].capacity, 800);
  });

  it('preview does not persist drums', () => {
    const stores = memoryImportStores();
    const rows = [
      {
        'Drum Code': 'EWD001',
        Flange: 1000,
        Barrel: 500,
        'Inner Width': 400,
        'Outer Width': 500,
        Capacity: 12,
      },
    ];
    const preview = previewKind('drums', rows, 'Drum List.xlsx', 'tester', { stores });
    assert.equal(preview.batch.status, 'PREVIEWED');
    assert.equal(stores.getDrums().length, 0);
    const commit = commitDrums(rows, 'Drum List.xlsx', 'tester', { persist: true, stores });
    assert.equal(commit.batch.status, 'COMMITTED');
    assert.equal(stores.getDrums().length, 1);
    assert.equal(stores.getDrums()[0].drumCode, 'EWD001');
    assert.equal(
      stores.getDrums()[0].description,
      'Wooden Drum F1000 x B500 x 400 x 500'
    );
  });

  it('imports drum description from Excel or auto-generates when blank', () => {
    const stores = memoryImportStores();
    const withDescription = commitDrums(
      [
        {
          'Drum Code': 'EWD630-0',
          Flange: 630,
          Barrel: 300,
          'Inner Width': 600,
          'Outer Width': 760,
          'Capacity / KG': 650,
          Description: 'Wooden Drum F630 x B300 x 600 x 760',
        },
      ],
      'Drum List.xlsx',
      'tester',
      { persist: true, stores }
    );
    assert.equal(withDescription.batch.status, 'COMMITTED');
    assert.equal(stores.getDrums()[0].description, 'Wooden Drum F630 x B300 x 600 x 760');
    assert.equal(stores.getDrums()[0].capacity, 650);

    const stores2 = memoryImportStores();
    const autoGenerated = commitDrums(
      [
        {
          'Drum Code': 'EWD700-3',
          Flange: 700,
          Barrel: 400,
          'Inner Width': 600,
          'Outer Width': 760,
          Capacity: 650,
        },
      ],
      'Drum List.xlsx',
      'tester',
      { persist: true, stores: stores2 }
    );
    assert.equal(autoGenerated.batch.status, 'COMMITTED');
    assert.equal(stores2.getDrums()[0].description, 'Wooden Drum F700 x B400 x 600 x 760');
  });

  it('imports optional Clearance / Max Load / Empty weight; Capacity remains source reference', () => {
    const stores = memoryImportStores();
    const result = commitDrums(
      [
        {
          'Drum Code': 'EWD630-0',
          Flange: 630,
          Barrel: 300,
          'Inner Width': 600,
          'Outer Width': 760,
          Capacity: 650,
          'Clearance Mm': 20,
          'Max Load Kg': 2000,
          'Empty Drum Net Weight Kg': 110,
        },
      ],
      'Drum List Engineering.xlsx',
      'tester',
      { persist: true, stores }
    );
    assert.equal(result.batch.status, 'COMMITTED');
    const drum = stores.getDrums()[0];
    assert.equal(drum.capacity, 650);
    assert.equal(drum.clearanceMm, 20);
    assert.equal(drum.maxWeight, 2000);
    assert.equal(drum.emptyDrumNetWeightKg, 110);
    assert.equal(drum.capacityUom, 'CONFIGURATION_REQUIRED');
  });

  it('TO rule: maps Capacity → MaxLoad and defaults Clearance 50 when engineering columns absent', () => {
    const stores = memoryImportStores();
    const result = commitDrums(
      [
        {
          'Drum Code': 'EWD630-0',
          Flange: 630,
          Barrel: 300,
          'Inner Width': 600,
          'Outer Width': 760,
          Capacity: 650,
        },
      ],
      'Drum List.xlsx',
      'tester',
      { persist: true, stores }
    );
    assert.equal(result.batch.status, 'COMMITTED');
    const drum = stores.getDrums()[0];
    assert.equal(drum.capacity, 650);
    assert.equal(drum.maxWeight, 650);
    assert.equal(drum.clearanceMm, 50);
    assert.equal(drum.emptyDrumNetWeightKg, null);
    assert.ok(result.batch.warnings.some((w) => /MaxLoad set from Capacity/i.test(w.message)));
    assert.ok(result.batch.warnings.some((w) => /Clearance Mm defaulted to 50/i.test(w.message)));
  });

  it('TO rule: blank Max Load Kg falls back to Capacity; blank Clearance defaults to 50', () => {
    const stores = memoryImportStores();
    const result = commitDrums(
      [
        {
          'Drum Code': 'EWD630-0',
          Flange: 630,
          Barrel: 300,
          'Inner Width': 600,
          'Outer Width': 760,
          Capacity: 650,
          'Clearance Mm': '',
          'Max Load Kg': '',
        },
      ],
      'Drum List Engineering.xlsx',
      'tester',
      { persist: true, stores }
    );
    assert.equal(result.batch.status, 'COMMITTED');
    const drum = stores.getDrums()[0];
    assert.equal(drum.capacity, 650);
    assert.equal(drum.maxWeight, 650);
    assert.equal(drum.clearanceMm, 50);
  });

  it('skips conflicting BOM cable+RM weights instead of auto-resolving or importing them', () => {
    const stores = memoryImportStores({
      cables: [
        {
          id: '1',
          itemCode: 'I1',
          cableCode: '10009487',
          customerCode: 'N2XH',
          code: 'N2XH 10009487',
          description: 'test',
          voltageClass: 'LV',
          conductor: 'Copper',
          cores: '1C',
          crossSectionMm2: 16,
          outerDiameterMm: 10.9,
          approxWeightKgKm: 268,
          standardPriceUsdPerM: 0,
          priceConfigured: false,
          status: 'ACTIVE',
        },
      ],
      rawMaterials: [
        {
          id: 'rm-CR01',
          rawMaterialCode: 'CR01',
          description: 'Copper',
          uom: 'kg',
          price: null,
          priceStatus: 'PRICE_NOT_CONFIGURED',
          status: 'ACTIVE',
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        },
      ],
    });
    const result = commitBoms(
      [
        {
          'Customer Code': 'N2XH',
          'Cable Material Number': '10009487',
          'Raw Material': 'CR01',
          Weight: 135.23,
          'Unit/Km': 'kg',
        },
        {
          'Customer Code': 'N2XH',
          'Cable Material Number': '10009487',
          'Raw Material': 'CR01',
          Weight: 140,
          'Unit/Km': 'kg',
        },
      ],
      'Energya Cable Master Data.xlsx',
      'tester',
      { persist: true, stores }
    );
    assert.equal(result.batch.status, 'COMMITTED');
    assert.equal(stores.getBoms().length, 0);
    assert.equal(result.batch.errorCount, 0);
    assert.ok((result.batch.skippedCount || 0) >= 2);
    assert.ok(result.duplicateObservations?.length === 1);
    assert.equal(result.duplicateObservations?.[0].classification, 'BUSINESS_DECISION_REQUIRED');
  });

  it('rejects duplicate drum codes without a partial save', () => {
    const stores = memoryImportStores();
    const result = commitDrums(
      [
        { 'Drum Code': 'EWD001', Flange: 1000, Barrel: 500, 'Inner Width': 400, 'Outer Width': 500, Capacity: 12 },
        { 'Drum Code': 'EWD001', Flange: 1100, Barrel: 500, 'Inner Width': 400, 'Outer Width': 500, Capacity: 12 },
      ],
      'Drum List.xlsx',
      'tester',
      { persist: true, stores }
    );
    assert.equal(result.batch.status, 'REJECTED');
    assert.equal(stores.getDrums().length, 0);
  });

  it('imports unique BOM lines while skipping only the conflicting group', () => {
    const stores = memoryImportStores({
      cables: [
        {
          id: '1',
          itemCode: 'I1',
          cableCode: '10009487',
          customerCode: 'N2XH',
          code: 'N2XH 10009487',
          description: 'test',
          voltageClass: 'LV',
          conductor: 'Copper',
          cores: '1C',
          crossSectionMm2: 16,
          outerDiameterMm: 10.9,
          approxWeightKgKm: 268,
          standardPriceUsdPerM: 0,
          priceConfigured: false,
          status: 'ACTIVE',
        },
      ],
      rawMaterials: [
        {
          id: 'rm-CR01',
          rawMaterialCode: 'CR01',
          description: 'Copper',
          uom: 'kg',
          price: null,
          priceStatus: 'PRICE_NOT_CONFIGURED',
          status: 'ACTIVE',
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        },
        {
          id: 'rm-PVC1',
          rawMaterialCode: 'PVC1',
          description: 'PVC',
          uom: 'kg',
          price: null,
          priceStatus: 'PRICE_NOT_CONFIGURED',
          status: 'ACTIVE',
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        },
      ],
    });
    const result = commitBoms(
      [
        {
          'Customer Code': 'N2XH',
          'Cable Material Number': '10009487',
          'Raw Material': 'CR01',
          Weight: 135.23,
          'Unit/Km': 'kg',
        },
        {
          'Customer Code': 'N2XH',
          'Cable Material Number': '10009487',
          'Raw Material': 'CR01',
          Weight: 140,
          'Unit/Km': 'kg',
        },
        {
          'Customer Code': 'N2XH',
          'Cable Material Number': '10009487',
          'Raw Material': 'PVC1',
          Weight: 20,
          'Unit/Km': 'kg',
        },
      ],
      'Energya Cable Master Data.xlsx',
      'tester',
      { persist: true, stores }
    );
    assert.equal(result.batch.status, 'COMMITTED');
    assert.equal(stores.getBoms().length, 1);
    assert.equal(stores.getBoms()[0].rawMaterial, 'PVC1');
    assert.equal(stores.getBoms()[0].weight, 20);
  });

  it('rejects a BOM line that references a missing Cable Master', () => {
    const stores = memoryImportStores({
      cables: [],
      rawMaterials: [
        {
          id: 'rm-CR01',
          rawMaterialCode: 'CR01',
          description: 'Copper',
          uom: 'kg',
          price: null,
          priceStatus: 'PRICE_NOT_CONFIGURED',
          status: 'ACTIVE',
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        },
      ],
    });
    const result = commitBoms(
      [
        {
          'Customer Code': 'N2XH',
          'Cable Material Number': 'MISSING-CABLE',
          'Raw Material': 'CR01',
          Weight: 10,
          'Unit/Km': 'kg',
        },
      ],
      'bom.xlsx',
      'tester',
      { persist: true, stores, enforceForeignKeys: true }
    );
    assert.equal(result.batch.status, 'REJECTED');
    assert.ok(result.batch.errors.some((e) => e.code === 'INVALID_REFERENCE'));
    assert.equal(stores.getBoms().length, 0);
  });
});
